### ISSUE TITLE
SDL 0248 - HMI Policy Table Update using vehicle modem

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/manticore#107]
Proposal: [HMI Policy Table Update using vehicle modem](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0248-hmi-ptu-support.md)

> This proposal describes an enhanced policy table update PTU sequence where the IVI system sends the policy table snapshots (PTS) directly to the policy server using the in-vehicle modem and returns a policy table update (PTU) back to SDL Core without using any SystemRequest RPC.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/813

**Comment by theresalech** [comment]
Included in Manticore 2.6: https://github.com/smartdevicelink/manticore/releases/tag/2.6.0.
