### ISSUE TITLE
Templates are not correct on reconnect to Manticore

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#11]
### Bug Report
When reconnecting to Manticore via the same socket after killing and restarting the app, the template is set to whatever was the last template in the previous session instead of the default template for the app type.

Also, attempting to change the template closes the Manticore app. The app icon then needs to be selected to reopen the app (the template is usually set correctly). I have to power off Manticore and get a new socket before templates start working again. 

##### Reproduction Steps
1. Connect the SDL_iOS example app to Manticore via the Xcode emulator. The example app type is `MEDIA`, so the default template is `MEDIA`.
1. Change the template to `LargeGraphicWithSoftButtons` (or any other supported template on Manticore)
1. Stop the Xcode emulator. Manticore will stop the session and the dialog box with the ip address and port number will appear.
1. Start the Xcode emulator and connect to Manticore using the ip address and port number from the dialog box in the above step.

##### Expected Behavior
The template should be set to MEDIA on reconnect. Templates should be changed successfully.

##### Observed Behavior
The template should be set to MEDIA on reconnect. Instead it is set to `LargeGraphicWithSoftButtons`. Changing the template closes the app on Manticore.

##### OS & Version Information
* iOS Version: iOS 11
* SDL iOS Version: 5.0.0
* Testing Against: Manticore, Chrome v. 61.0.3163.100

##### Test Case, Sample Code, and / or Example App
The SDL Example app is included with the [SDL_iOSlibrary](https://github.com/smartdevicelink/sdl_ios)

**Comment by crokita** [comment]
Will be resolved on the next Manticore release

**Comment by crokita** [comment]
Resolved with the #52 2.0.0 release
