### ISSUE TITLE
Manticore UI policy server URL change

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/manticore#111]
Investigate utilizing the policy server URL change field in the Manticore UI and whether it is functioning as intended. If not, report here with specifics on what's wrong.

**Comment by renonick87** [comment]
Attempting to set the Policy URL before an app is connected causes the PTU to fail, and apps will not get another OnSystemRequest making PTUs not possible. This also disables the functionality of the app shopping cart icon in the HMI.
