### ISSUE TITLE
authToken is not set correctly in the StartServiceAck

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/manticore#114]
It seems that the`authToken` is not set correctly in the `StartServiceAck` in Manticore even if it is set correctly when adding a cloud app in Manticore UI. That same thing worked well for me when using Core in my VM.
https://github.com/smartdevicelink/protocol_spec#31322-start-service-ack

**Comment by theresalech** [comment]
Issue closed via https://github.com/smartdevicelink/sdl_core/pull/3870, which was included in Manticore 2.10 release.
