### ISSUE TITLE
Toggling the HMI theme is broken

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#138]
Toggling the HMI theme (i.e. selecting the “Dark” and “Light” button under “Change HMI Theme”) is broken on Manticore. I tested the same app on generic HMI and switching the HMI theme worked as expected. 

I was using Firefox Developer Edition when testing.

**Comment by crokita** [comment]
Fix introduced in generic_hmi minimal-0.10.0 branch:
https://github.com/smartdevicelink/generic_hmi/commit/a6cf127e4316ecb70dff2b1f36f68f8fa26c7707
