### ISSUE TITLE
PerformInteractions sent quickly after CICS RPCs do not cause highlighted VR commands in the Manticore UI 

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/manticore#143]
The Manticore UI adds and removes VR commands in batches in order to handle large amounts of commands at once to increase performance. This does cause the commands to be more asynchronous and there is a chance that an app can send a performinteraction too soon which causes the performinteraction to be processed before adding the VR commands for that interaction. 

Manticore UI shows all commands uploaded by apps, but when a performinteraction comes and makes some of the commands selectable, all the selected commands should turn blue to indicate they can be clicked on in the voice tab.
The issue is that sometimes the performinteraction comes first before the commands are uploaded, so the commands will still show up but they will not be highlighted as selectable

**Comment by theresalech** [comment]
Closed via https://gitlab.com/smartdevicelink/web/sdl-web/-/merge_requests/1292
