### ISSUE TITLE
UpdateDeviceList RPC spam due to TCP health check

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/manticore#164]
There is a repeated spam of UpdateDeviceList RPCs that the HMI receives. This is because core detects a new device connect and then disconnect every 3 seconds. This aligns with the 3 second interval health check that the Consul program uses to make sure that core's TCP port is healthy. Since the server and docker containers are fairly stable at this point I recommend removing the health check to the TCP port: there are many other health checks done to other ports of the core container to ensure its operation anyway.

**Comment by theresalech** [comment]
Closed via #165
