### ISSUE TITLE
Menu needs a back button

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#17]
## Bug Report
Manticore's menu does not have a back button. This means that the user is forced to select a menu item in order to exit the menu. This is an issue because I often accidentally open the menu and I just want to close it. In addition, if the menu is empty, there is no way to exit the menu.

### OS & Version Information
Manticore Version: 1.2.0
Web Browser: Chrome v. 65.0.3325.181

**Comment by crokita** [comment]
The newest release of hosted Manticore on the developer portal has the latest Generic HMI version which includes a back button while in the menu.
