### ISSUE TITLE
Webengine apps do not reappear in the sidebar if the Manticore dev portal page refreshes

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/manticore#172]
This is similar to this issue: #170 

The webengine app list on the sidebar is gone when refreshing the Manticore page and getting your same instance back. The Manticore UI should take measures to recreate the list so that the installed webengine apps can be removed if desired.

**Comment by theresalech** [comment]
Resolved via https://github.com/smartdevicelink/manticore-images/pull/32
