### ISSUE TITLE
VR commands are not reset or deleted properly

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#18]
## Bug Report
1. When a `DeleteCommand` is sent, the corresponding voice command in the VR menu of Manticore should be removed from the list. Currently nothing happens when the `DeleteCommand` was sent successfully.
1. When the app disconnects from Manticore, all items in the VR menu of Manticore should be deleted. Currently the voice commands from the previous session are visible. The only way to empty the VR list is power down Manticore. 

### OS & Version Information
Manticore Version: 1.2.0
SDL Core Version: 4.4.1
Web Browser: Chrome v. 65.0.3325.181

**Comment by theresalech** [comment]
Fixed via `DeleteInteractionChoiceSet` bug fix.

**Comment by crokita** [comment]
Fixing the bug for deleting commands also fixed the issue for deleting interaction choice sets, which can also contain VR commands. The UI handles the DeleteCommand RPC for both types of VR commands and is working.
