### ISSUE TITLE
FuelRange Manticore UI Updates

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/manticore#181]
Based on accepted SDL Evolution Proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md, we need to:
* Update `FuelRange` Struct to include:
   * `type` (existing)
   * `range` (existing)
   * `fuelLevel` (moved)
   * `fuelLevel_State` (moved)
   * `capacity` (new)
   * `capacityUnit` (new)
* Add new enum `CapacityUnit`.
* Deprecate vehicle data `fuelLevel`.
* Deprecate vehicle data `fuelLevel_State`.

This will need to be reflected in the Manticore UI.

**Comment by crokita** [comment]
Manticore UI updated on the SmartDeviceLink dev portal.
