### ISSUE TITLE
Part of the alert box extends off the screen

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/manticore#55]
### Bug Report
When showing an alert on Manticore, part of the alert box extends off the screen.

On generic_hmi, it looks like the entire background is darkened, so it looks like the entire view is slightly offset on Manticore.

##### Reproduction Steps
1. Connect app to Manticore
1. Send a `SDLAlert` RPC

##### Expected Behavior
The alert box should be centered on the screen.

##### Observed Behavior
The alert box extends off the screen

##### OS & Version Information
* Web Browser: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
* HMI Version: Generic HMI v0.5.1.
* Core Version:  SDL Core v5.0.1

##### Test Case, Sample Code, and / or Example App
![manticore alert bug](https://user-images.githubusercontent.com/19915981/49242395-9ef2d500-f3d8-11e8-8b2e-51e397bb5365.png)

**Comment by crokita** [comment]
The alert box is now aligned properly
