### ISSUE TITLE
Driver Distraction Notifications Needed

### ISSUE THREAD

**Issue by brettywhite** [smartdevicelink/manticore#9]
Manticore should support DD Notifications (DD_On and DD_Off). This is a major point of testing needed for all applications that use the SDL library.

1. There should be a switch that allows Moving (DD_On) and Parked (DD_Off) to be triggered manually.
2. When the speed slider is set to 0, a DD_Off notification should be sent. When speed != 0, a DD_On notification should be sent

**Comment by crokita** [comment]
The newest release of hosted Manticore on the developer portal now includes a driver distraction toggle in the Settings tab of the UI.

Automatic notifications sent based on speed have been decided to not be included.
